enable: true # è®¾ç½®ä¸º false å…³é—­æ‰€æœ‰ awesome-gitlab ç‰¹æ€§
plugins:
  click_to_copy: true # ç‚¹å‡» issue/mr å¼•ç”¨è‡ªåŠ¨å¤åˆ¶
  confirm_mr_merge:
    enable: true # MR +n è¦æ±‚é»˜è®¤å…³é—­
    branch: '**' # åªåœ¨åˆå¹¶åˆ°ç‰¹å®šåˆ†æ”¯å¼€å¯ï¼Œé»˜è®¤æ‰€æœ‰ï¼Œå¦‚ï¼šè®¾ç½®åªåœ¨ master å¼€å¯
    voteUpThreshold: 1 # MR +n è¦æ±‚é˜ˆå€¼
    voteUpTip: 'å°‘å¹´ï¼ŒMR +1 æœªæ»¡ï¼Œåˆå¹¶ä½ å°±æ‘Šä¸Šå¤§äº‹äº†ï¼ğŸ˜' # ä¸è¶³ +n æç¤º
    voteDownTip: 'åˆæ°‘ï¼Œæœ‰ -1 çš„ MR ä¹Ÿæƒ³åˆï¼Ÿ' # å­˜åœ¨ -1 æç¤º
  description_templates: true # å¼€å¯ issue/MR/milestone æ¨¡ç‰ˆ
  linkify_all: true # MR é¡µé¢åˆ†æ”¯é“¾æ¥
  obelisk: true # obelisk å‘å¸ƒå¿«æ·é“¾æ¥
  remove_source_branch: true # MR åˆå¹¶æ—¶é»˜è®¤é€‰ä¸­åˆå¹¶åç§»é™¤æºåˆ†æ”¯
  preload_mr: true # MR é¢„å…ˆåŠ è½½ commits & changes
  toggle_comment: true # å±•å¼€ MR è¯„è®ºå…¨éƒ¨å¯¹è¯
  zen_mode_preview: true # markdown ç¼–è¾‘å™¨ zen æ¨¡å¼å¼€å¯å¿«æ·é”®
